token-urls
tombola/wagtail-sharing pull request #1
Opened 2020-07-30 16:07 UTC by tombola

Short description explaining the high-level reason for the pull request

## Additions

-

## Removals

-

## Changes

-

## Testing

-

## Review

- @user

[Preview this PR without the whitespace changes](?w=0)

## Screenshots

## Notes

-

## Todos

-

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

2020-07-31 10:41 UTC, tombola commented
I added and then removed `--recursive` option for isort, it is apparently not needed any more, I must have had old version of isort installed.

Also looks like my vscode was not using isort for python import sorts for some reason, so conflicted with tests, ran isort manually from cli should now pass....

2020-08-06 08:02 UTC, zerolab requested changes

2020-08-06 08:02 UTC, zerolab commented on CONTRIBUTING.md
> +isort wagtailsharing
isort 5.x does recursive by default - https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/

2020-08-06 08:02 UTC, zerolab commented on wagtailsharing/views.py
> +        sharing_site = self.get_sharing_site(request, path)
should only react to GET requests

2020-08-06 08:02 UTC, zerolab commented on README.rst
> +
worth adding a note that in some environments such as Heroku, `SERVER_PORT` set at release time and the real port is fowarded, so `USE_X_FORWARDED_PORT = True` is needed in settings

2020-08-07 08:15 UTC, zerolab commented on setup.py
>      "wagtail>=2.3,<2.10",
```suggestion
    "wagtail>=2.3,<2.11",
```

since we're running on 2.10rc1

2020-08-11 10:19 UTC, zerolab commented
Nice one. Why not open a WIP PR against the main repo to get any further feedback. Will see if I can provide tests

2020-12-08 18:59 UTC, zerolab commented
@tombola would be great if you could submit this as a PR against the main repo

2021-10-25 10:39 UTC, closed without merging